name: Test No Out Hours Merge Action

on:
    pull_request:
        types: [opened, synchronize, edited]
    push:
        branches:
            - master

concurrency:
    group: environment-${{ github.ref }}
    cancel-in-progress: true

permissions:
    issues: write
    pull-requests: write

jobs:
    test:
        name: Test github action üß™
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Import .env File
              shell: bash
              run: cat .env >>${GITHUB_ENV}

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements-dev.txt

            - name: Run tests üß™
              run: |
                  python -m unittest discover -t ./src/ -s ./src/tests

            - name: Test Restrict PR Merge Action üß™
              uses: ./ # Use an action in the same repository
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TIMEZONE: Australia/Sydney
                  RESTRICTED_TIMES: >-
                      {
                        "weekly": [
                          {
                            "days": ["mon", "tue", "wed", "thu", "fri"],
                            "intervals": [[0, 1]]
                          }
                        ],
                        "dates": [],
                        "holidays": {}
                      }
                  CUSTOM_MESSAGE: ‚ö†Ô∏è **PR merging is not allowed outside business hours.** ‚ö†Ô∏è
                  CHECK_EXISTING_COMMENT: 'true'
